### ISSUE TITLE
Question: How to re-center if content in the modal changes?

### ISSUE THREAD

**Issue by tsteuwer** [yapplabs/ember-modal-dialog#147]
I don't see a way to do this without hacking addon to figure this out. Any thoughts on this would be much appreciated.

**Comment by rossanthony** [comment]
I'm also wondering about this, I have a modal which contains conditional content and when the user choses a particular option the height of the modal increases, potentially (on small displays) making part of the modal inaccessible as it hangs outside the viewport. It doesn't look like there is currently a way of triggering the recalculation of the margin-top offset, although in theory it shouldn't be too hard to add this functionality in.

**Comment by stevenwanderski** [comment]
To achieve horizontal and vertical centering even after the contents change size, I use the following CSS override:

```css
.ember-modal-dialog {
  /* The library calculates the margin-left
  and margin-right values using JS, and does
  not re-calculate if the content inside the 
  modal changes its size.
  The following lines keep the modal
  horizontally and vertically centered
  even after inner content changes sizes.*/
  margin-left: auto !important;
  margin-top: auto !important;
  transform: translate(-50%, -50%);
}
```
