### ISSUE TITLE
Animated, centered and vertically scrollable dialog

### ISSUE THREAD

**Issue by Turbo87** [yapplabs/ember-modal-dialog#216]
I've been using `ember-modal-dialog` with `liquid-wormhole` to create centered dialogs and everything worked fine. At some point I noticed a problem though because the dialog was larger than the browser window and it wasn't possible to scroll. It seems that the DOM structure that `ember-modal-dialog` currently produces is not fit for this task.

For future reference my solution to this was unfortunately to ditch `ember-modal-dialog` completely and use `liquid-wormhole` directly like this:

```hbs
{{#liquid-wormhole class="modal-dialog-container"}}
  <div class="modal-dialog-overlay" onclick={{action onClose}}></div>

  {{! This crazy stuff makes the dialog both centered *and* vertically scrollable }}
  <div class="modal-dialog-table-wrapper">
    <div class="modal-dialog-table-cell-wrapper">
      <div class="modal-dialog {{containerClass}}">
        {{yield}}
      </div>
    </div>
  </div>
{{/liquid-wormhole}}
```

```css
.modal-dialog-container {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100vh;

  overflow-y: auto;
}

.modal-dialog-table-wrapper {
  display: table;
  width: 100%;
  height: 100%;
}

.modal-dialog-table-cell-wrapper {
  display: table-cell;
  vertical-align: middle;
}

.modal-dialog {
  position: relative;
  margin: 20px auto;
  z-index: 123;
}
```
