### ISSUE TITLE
Safari auto-center modal

### ISSUE THREAD

**Issue by nizarayari** [yapplabs/ember-modal-dialog#251]
On safari I wasn't able to re-center the modal content when I insert dynamically content on the modal.

I had to use this CSS working in every browser

```css
.ember-modal-wrapper.emd-static.emd-wrapper-target-attachment-center .ember-modal-dialog {
  position: absolute;
  top: 50%;
  -ms-transform: translateY(-50%);
  -webkit-transform: translateY(-50%);
  -moz-transform: translateY(-50%);
  -o-transform: translateY(-50%);
  transform: translateY(-50%);
}
```

That's sounds correct for you?
