### ISSUE TITLE
Avoid Sass dependency

### ISSUE THREAD

**Issue by samselikoff** [yapplabs/ember-modal-dialog#257]
Believe vanilla `app.css` can `@import 'ember-modal-dialog.css'` these days, we should lay out the path to removing the `scss` dependency and providing the styles for any stack.

**Comment by chrism** [comment]
I completely agree with this and would be happy to do the work.

I did something similar for Ember Tooltips some time ago https://github.com/sir-dunxalot/ember-tooltips/pull/264

Also, it seems like 3.0.0 would be a good moment to implement it?

**Most basic approach**

The SCSS could just be flattened into CSS so [ember-modal-structure.scss](https://github.com/yapplabs/ember-modal-dialog/blob/master/app/styles/ember-modal-dialog/ember-modal-structure.scss) becomes

```css
.ember-modal-dialog {
  z-index: 51;
  position: fixed;
}

.ember-modal-dialog.emd-in-place {
  position: static;
}

.ember-modal-wrapper.emd-static.emd-wrapper-target-attachment-center .ember-modal-dialog {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.ember-modal-wrapper.emd-animatable .ember-modal-dialog {
  position: relative;
}

.ember-modal-wrapper.emd-animatable.emd-wrapper-target-attachment-center {
  width: 100vw;
  height: 100vh;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 50;
  display: flex;
  align-items: center;
  justify-content: center;
}

.ember-modal-wrapper.emd-animatable.emd-wrapper-target-attachment-center .ember-modal-overlay {
  display: flex;
  align-items: center;
  justify-content: center;
}

.ember-modal-overlay {
  width: 100vw;
  height: 100vh;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 50;
}
```

and stays the same just changes to `.css`

```css
.ember-modal-dialog {
  border-radius: 8px;
  background-color: #fff;
  box-shadow: 0 0 10px #222;
  padding: 10px;
}
.ember-modal-overlay.translucent {
  background-color: rgba(#808080, .77);
}
```

This would be enough to offer the option for non-SASS users as well and to include the css via

```
@import "ember-modal-dialog/ember-modal-structure.css";
@import "ember-modal-dialog/ember-modal-appearance.css";
```

without forcing the installation of `ember-cli-sass`.

**More ambitious option**

But it could also be taken further and to remove the files and the dev dependency for `ember-cli-sass` completely.

This would mean a breaking change, but a very simple one to fix (just add the extension to the css files).

It would also mean updating the CSS in the dummy app to no longer rely on SASS—which is something that I'd be happy to implement if it will be merged.

Then `ember-cli-sass` could be removed completely as a dependency.

Let me know if either option is acceptable and I will submit a PR.

Thanks.
