### ISSUE TITLE
top-center alignment

### ISSUE THREAD

**Issue by samselikoff** [yapplabs/ember-modal-dialog#8]
How would I go about getting my modal to align top-and-center?

**Comment by chrislopresto** [comment]
Your best bet for now is to specify `alignment='none'` and provide your own custom css like this:

```handlebars
{{#modal-dialog alignment='none'
                overlayClassNames='make-me-top-and-center' }}
  <h1>Stop! Modal Time!</h1>
  <p>Custom Styles</p>
{{/modal-dialog}}
```

```css
.make-me-top-and-center {
  position: fixed;
  left: 0;
  right: 0;
  margin: 0 auto;
  top: 10px;
  width: 300px;
  z-index: 100000;
}
```

We should update the docs to make it more obvious that you need to override/unwire the default alignment.
